resolver: lts-14.11
packages:
- .
extra-deps:
  - git: https://github.com/cryptiumlabs/jsonschema-gen.git
    commit: 0639cd166ec59a04d07a3a7d49bdf343e567000e
flags: {}
extra-package-dbs: []
compiler-check: newer-minor
